// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "BuildTimeOptimized",
    products: [.executable(name: "Demo", targets: ["Demo"])],
    targets: [
        .target(name: "Shared"),
        .target(name: "Feature01Domain", dependencies: ["Shared"]),
        .target(name: "Feature01Data", dependencies: ["Feature01Domain"]),
        .target(name: "Feature01Presentation", dependencies: ["Feature01Domain", "Feature01Data"]),
        .target(name: "Feature02Domain", dependencies: ["Shared"]),
        .target(name: "Feature02Data", dependencies: ["Feature02Domain"]),
        .target(name: "Feature02Presentation", dependencies: ["Feature02Domain", "Feature02Data"]),
        .target(name: "Feature03Domain", dependencies: ["Shared"]),
        .target(name: "Feature03Data", dependencies: ["Feature03Domain"]),
        .target(name: "Feature03Presentation", dependencies: ["Feature03Domain", "Feature03Data"]),
        .target(name: "Feature04Domain", dependencies: ["Shared"]),
        .target(name: "Feature04Data", dependencies: ["Feature04Domain"]),
        .target(name: "Feature04Presentation", dependencies: ["Feature04Domain", "Feature04Data"]),
        .target(name: "Feature05Domain", dependencies: ["Shared"]),
        .target(name: "Feature05Data", dependencies: ["Feature05Domain"]),
        .target(name: "Feature05Presentation", dependencies: ["Feature05Domain", "Feature05Data"]),
        .target(name: "Feature06Domain", dependencies: ["Shared"]),
        .target(name: "Feature06Data", dependencies: ["Feature06Domain"]),
        .target(name: "Feature06Presentation", dependencies: ["Feature06Domain", "Feature06Data"]),
        .target(name: "Feature07Domain", dependencies: ["Shared"]),
        .target(name: "Feature07Data", dependencies: ["Feature07Domain"]),
        .target(name: "Feature07Presentation", dependencies: ["Feature07Domain", "Feature07Data"]),
        .target(name: "Feature08Domain", dependencies: ["Shared"]),
        .target(name: "Feature08Data", dependencies: ["Feature08Domain"]),
        .target(name: "Feature08Presentation", dependencies: ["Feature08Domain", "Feature08Data"]),
        .target(name: "Feature09Domain", dependencies: ["Shared"]),
        .target(name: "Feature09Data", dependencies: ["Feature09Domain"]),
        .target(name: "Feature09Presentation", dependencies: ["Feature09Domain", "Feature09Data"]),
        .target(name: "Feature10Domain", dependencies: ["Shared"]),
        .target(name: "Feature10Data", dependencies: ["Feature10Domain"]),
        .target(name: "Feature10Presentation", dependencies: ["Feature10Domain", "Feature10Data"]),
        .target(name: "Feature11Domain", dependencies: ["Shared"]),
        .target(name: "Feature11Data", dependencies: ["Feature11Domain"]),
        .target(name: "Feature11Presentation", dependencies: ["Feature11Domain", "Feature11Data"]),
        .target(name: "Feature12Domain", dependencies: ["Shared"]),
        .target(name: "Feature12Data", dependencies: ["Feature12Domain"]),
        .target(name: "Feature12Presentation", dependencies: ["Feature12Domain", "Feature12Data"]),
        .target(name: "Feature13Domain", dependencies: ["Shared"]),
        .target(name: "Feature13Data", dependencies: ["Feature13Domain"]),
        .target(name: "Feature13Presentation", dependencies: ["Feature13Domain", "Feature13Data"]),
        .target(name: "Feature14Domain", dependencies: ["Shared"]),
        .target(name: "Feature14Data", dependencies: ["Feature14Domain"]),
        .target(name: "Feature14Presentation", dependencies: ["Feature14Domain", "Feature14Data"]),
        .target(name: "Feature15Domain", dependencies: ["Shared"]),
        .target(name: "Feature15Data", dependencies: ["Feature15Domain"]),
        .target(name: "Feature15Presentation", dependencies: ["Feature15Domain", "Feature15Data"]),
        .target(name: "Feature16Domain", dependencies: ["Shared"]),
        .target(name: "Feature16Data", dependencies: ["Feature16Domain"]),
        .target(name: "Feature16Presentation", dependencies: ["Feature16Domain", "Feature16Data"]),
        .target(name: "Feature17Domain", dependencies: ["Shared"]),
        .target(name: "Feature17Data", dependencies: ["Feature17Domain"]),
        .target(name: "Feature17Presentation", dependencies: ["Feature17Domain", "Feature17Data"]),
        .target(name: "Feature18Domain", dependencies: ["Shared"]),
        .target(name: "Feature18Data", dependencies: ["Feature18Domain"]),
        .target(name: "Feature18Presentation", dependencies: ["Feature18Domain", "Feature18Data"]),
        .target(name: "Feature19Domain", dependencies: ["Shared"]),
        .target(name: "Feature19Data", dependencies: ["Feature19Domain"]),
        .target(name: "Feature19Presentation", dependencies: ["Feature19Domain", "Feature19Data"]),
        .target(name: "Feature20Domain", dependencies: ["Shared"]),
        .target(name: "Feature20Data", dependencies: ["Feature20Domain"]),
        .target(name: "Feature20Presentation", dependencies: ["Feature20Domain", "Feature20Data"]),
        .target(name: "Feature21Domain", dependencies: ["Shared"]),
        .target(name: "Feature21Data", dependencies: ["Feature21Domain"]),
        .target(name: "Feature21Presentation", dependencies: ["Feature21Domain", "Feature21Data"]),
        .target(name: "Feature22Domain", dependencies: ["Shared"]),
        .target(name: "Feature22Data", dependencies: ["Feature22Domain"]),
        .target(name: "Feature22Presentation", dependencies: ["Feature22Domain", "Feature22Data"]),
        .target(name: "Feature23Domain", dependencies: ["Shared"]),
        .target(name: "Feature23Data", dependencies: ["Feature23Domain"]),
        .target(name: "Feature23Presentation", dependencies: ["Feature23Domain", "Feature23Data"]),
        .target(name: "Feature24Domain", dependencies: ["Shared"]),
        .target(name: "Feature24Data", dependencies: ["Feature24Domain"]),
        .target(name: "Feature24Presentation", dependencies: ["Feature24Domain", "Feature24Data"]),
        .target(name: "Feature25Domain", dependencies: ["Shared"]),
        .target(name: "Feature25Data", dependencies: ["Feature25Domain"]),
        .target(name: "Feature25Presentation", dependencies: ["Feature25Domain", "Feature25Data"]),
        .target(name: "Feature26Domain", dependencies: ["Shared"]),
        .target(name: "Feature26Data", dependencies: ["Feature26Domain"]),
        .target(name: "Feature26Presentation", dependencies: ["Feature26Domain", "Feature26Data"]),
        .target(name: "Feature27Domain", dependencies: ["Shared"]),
        .target(name: "Feature27Data", dependencies: ["Feature27Domain"]),
        .target(name: "Feature27Presentation", dependencies: ["Feature27Domain", "Feature27Data"]),
        .target(name: "Feature28Domain", dependencies: ["Shared"]),
        .target(name: "Feature28Data", dependencies: ["Feature28Domain"]),
        .target(name: "Feature28Presentation", dependencies: ["Feature28Domain", "Feature28Data"]),
        .target(name: "Feature29Domain", dependencies: ["Shared"]),
        .target(name: "Feature29Data", dependencies: ["Feature29Domain"]),
        .target(name: "Feature29Presentation", dependencies: ["Feature29Domain", "Feature29Data"]),
        .target(name: "Feature30Domain", dependencies: ["Shared"]),
        .target(name: "Feature30Data", dependencies: ["Feature30Domain"]),
        .target(name: "Feature30Presentation", dependencies: ["Feature30Domain", "Feature30Data"]),
        .target(name: "Feature31Domain", dependencies: ["Shared"]),
        .target(name: "Feature31Data", dependencies: ["Feature31Domain"]),
        .target(name: "Feature31Presentation", dependencies: ["Feature31Domain", "Feature31Data"]),
        .target(name: "Feature32Domain", dependencies: ["Shared"]),
        .target(name: "Feature32Data", dependencies: ["Feature32Domain"]),
        .target(name: "Feature32Presentation", dependencies: ["Feature32Domain", "Feature32Data"]),
        .target(name: "Feature33Domain", dependencies: ["Shared"]),
        .target(name: "Feature33Data", dependencies: ["Feature33Domain"]),
        .target(name: "Feature33Presentation", dependencies: ["Feature33Domain", "Feature33Data"]),
        .executableTarget(name: "Demo", dependencies: ["Feature01Presentation", "Feature02Presentation", "Feature03Presentation", "Feature04Presentation", "Feature05Presentation", "Feature06Presentation", "Feature07Presentation", "Feature08Presentation", "Feature09Presentation", "Feature10Presentation", "Feature11Presentation", "Feature12Presentation", "Feature13Presentation", "Feature14Presentation", "Feature15Presentation", "Feature16Presentation", "Feature17Presentation", "Feature18Presentation", "Feature19Presentation", "Feature20Presentation", "Feature21Presentation", "Feature22Presentation", "Feature23Presentation", "Feature24Presentation", "Feature25Presentation", "Feature26Presentation", "Feature27Presentation", "Feature28Presentation", "Feature29Presentation", "Feature30Presentation", "Feature31Presentation", "Feature32Presentation", "Feature33Presentation"])
    ]
)
