// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "BuildTimeBaseline",
    products: [.executable(name: "Demo", targets: ["Demo"])],
    dependencies: [.package(path: "Packages/Feature01Presentation"),
        .package(path: "Packages/Feature02Presentation"),
        .package(path: "Packages/Feature03Presentation"),
        .package(path: "Packages/Feature04Presentation"),
        .package(path: "Packages/Feature05Presentation"),
        .package(path: "Packages/Feature06Presentation"),
        .package(path: "Packages/Feature07Presentation"),
        .package(path: "Packages/Feature08Presentation"),
        .package(path: "Packages/Feature09Presentation"),
        .package(path: "Packages/Feature10Presentation"),
        .package(path: "Packages/Feature11Presentation"),
        .package(path: "Packages/Feature12Presentation"),
        .package(path: "Packages/Feature13Presentation"),
        .package(path: "Packages/Feature14Presentation"),
        .package(path: "Packages/Feature15Presentation"),
        .package(path: "Packages/Feature16Presentation"),
        .package(path: "Packages/Feature17Presentation"),
        .package(path: "Packages/Feature18Presentation"),
        .package(path: "Packages/Feature19Presentation"),
        .package(path: "Packages/Feature20Presentation"),
        .package(path: "Packages/Feature21Presentation"),
        .package(path: "Packages/Feature22Presentation"),
        .package(path: "Packages/Feature23Presentation"),
        .package(path: "Packages/Feature24Presentation"),
        .package(path: "Packages/Feature25Presentation"),
        .package(path: "Packages/Feature26Presentation"),
        .package(path: "Packages/Feature27Presentation"),
        .package(path: "Packages/Feature28Presentation"),
        .package(path: "Packages/Feature29Presentation"),
        .package(path: "Packages/Feature30Presentation"),
        .package(path: "Packages/Feature31Presentation"),
        .package(path: "Packages/Feature32Presentation"),
        .package(path: "Packages/Feature33Presentation")],
    targets: [.executableTarget(name: "Demo", dependencies: [.product(name: "Feature01Presentation", package: "Feature01Presentation"), .product(name: "Feature02Presentation", package: "Feature02Presentation"), .product(name: "Feature03Presentation", package: "Feature03Presentation"), .product(name: "Feature04Presentation", package: "Feature04Presentation"), .product(name: "Feature05Presentation", package: "Feature05Presentation"), .product(name: "Feature06Presentation", package: "Feature06Presentation"), .product(name: "Feature07Presentation", package: "Feature07Presentation"), .product(name: "Feature08Presentation", package: "Feature08Presentation"), .product(name: "Feature09Presentation", package: "Feature09Presentation"), .product(name: "Feature10Presentation", package: "Feature10Presentation"), .product(name: "Feature11Presentation", package: "Feature11Presentation"), .product(name: "Feature12Presentation", package: "Feature12Presentation"), .product(name: "Feature13Presentation", package: "Feature13Presentation"), .product(name: "Feature14Presentation", package: "Feature14Presentation"), .product(name: "Feature15Presentation", package: "Feature15Presentation"), .product(name: "Feature16Presentation", package: "Feature16Presentation"), .product(name: "Feature17Presentation", package: "Feature17Presentation"), .product(name: "Feature18Presentation", package: "Feature18Presentation"), .product(name: "Feature19Presentation", package: "Feature19Presentation"), .product(name: "Feature20Presentation", package: "Feature20Presentation"), .product(name: "Feature21Presentation", package: "Feature21Presentation"), .product(name: "Feature22Presentation", package: "Feature22Presentation"), .product(name: "Feature23Presentation", package: "Feature23Presentation"), .product(name: "Feature24Presentation", package: "Feature24Presentation"), .product(name: "Feature25Presentation", package: "Feature25Presentation"), .product(name: "Feature26Presentation", package: "Feature26Presentation"), .product(name: "Feature27Presentation", package: "Feature27Presentation"), .product(name: "Feature28Presentation", package: "Feature28Presentation"), .product(name: "Feature29Presentation", package: "Feature29Presentation"), .product(name: "Feature30Presentation", package: "Feature30Presentation"), .product(name: "Feature31Presentation", package: "Feature31Presentation"), .product(name: "Feature32Presentation", package: "Feature32Presentation"), .product(name: "Feature33Presentation", package: "Feature33Presentation")])]
)
